services:
  - type: web
    name: estate-practice
    env: docker
    buildCommand: composer install --no-interaction --no-dev
    startCommand: "/start.sh"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"